Feat/solana integration
LedgerHQ/wallet-api pull request #132
Opened 2023-03-14 12:16 UTC by RamyEB

## Solana integration 

- [x] Created a new family 
- [x] Added tests

2023-03-24 08:41 UTC, JunichiSugiura requested changes

2023-03-24 08:41 UTC, JunichiSugiura commented on packages/core/src/families/solana/types.ts
> +  readonly family: RawSolanaTransaction["family"];
Missing transaction model field.

https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/families/solana/types.ts#L175

2023-03-29 13:07 UTC, cksanders commented on packages/core/src/families/solana/serializer.ts
> +    recipient,
model is required. https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/families/solana/transaction.ts#L34

2023-03-29 13:07 UTC, cksanders commented on packages/core/src/families/solana/serializer.ts
> +    recipient,
add model https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/families/solana/transaction.ts#L34

2023-03-29 13:08 UTC, cksanders commented on packages/core/tests/serializers.spec.ts
> +          recipient: "recipient",
add model

2023-03-29 13:08 UTC, cksanders commented on packages/core/tests/serializers.spec.ts
> +      it("should succeed to serialize a solana transaction with resource and duration", () => {
```suggestion
      it("should serialize a Solana transaction", () => {
```

2023-03-29 13:09 UTC, cksanders commented on packages/core/tests/serializers.spec.ts
> +    });
remove dup test

2023-03-29 13:09 UTC, cksanders commented on packages/core/tests/serializers.spec.ts
> +    });
remove dup test

2023-03-29 13:09 UTC, cksanders commented on packages/core/tests/serializers.spec.ts
> +      it("should succeed to deserialize a solana transaction with resource and duration", () => {
```suggestion
      it("should serialize an Elrond transaction", () => {
```

2023-04-04 13:39 UTC, JunichiSugiura requested changes
`npx changelog` to generate just in case. Then LGTM.

2023-04-04 13:57 UTC, JunichiSugiura requested changes
Sorry, one more thing

2023-04-04 13:57 UTC, JunichiSugiura commented on packages/core/src/families/solana/types.ts
> +  model: object;
It should be typed.

2023-04-04 13:57 UTC, JunichiSugiura commented on packages/core/src/families/solana/validation.ts
> +  model: z.string(),
hmm, is this a stringified object?

2023-04-04 15:01 UTC, RamyEB commented on packages/core/src/families/solana/validation.ts
> +  model: z.string(),
yep

2023-04-05 13:33 UTC, cksanders approved these changes

2023-04-05 13:34 UTC, merged