added an optional meta object param to all sign transactions
LedgerHQ/wallet-api pull request #159
Opened 2023-04-17 11:11 UTC by IAmMorrow

#149 

This meta object can be used to pass wallet specific data

2023-04-26 12:37 UTC, adrienlacombe-ledger commented
https://github.com/LedgerHQ/wallet-api/issues/149

2023-04-27 08:22 UTC, Justkant requested changes
Only one small change

2023-04-27 08:22 UTC, Justkant commented on packages/server/src/types.ts
> +    meta?: unknown;
```suggestion
    meta?: Record<string, unknown>;
```

2023-04-27 08:22 UTC, Justkant commented on packages/server/src/types.ts
> +    meta?: unknown;
```suggestion
    meta?: Record<string, unknown>;
```

2023-04-27 08:22 UTC, Justkant commented on packages/server/src/types.ts
> +    meta?: unknown;
```suggestion
    meta?: Record<string, unknown>;
```

2023-04-27 08:27 UTC, Justkant approved these changes

2023-04-27 09:07 UTC, merged