Details to manifest page
LedgerHQ/wallet-api pull request #196
Opened 2023-06-19 16:23 UTC by RamyEB

2023-06-21 08:45 UTC, ComradeAERGO requested changes

2023-06-21 13:22 UTC, adrienlacombe-ledger commented on apps/docs/pages/appendix/manifest.mdx
> +| visibility       | Visibility of your live app inside Ledger Live | string          | "complete", "searchable", "deep"  |
correct @RamyEB

2023-06-21 13:23 UTC, adrienlacombe-ledger commented on apps/docs/pages/appendix/manifest.mdx
> +| visibility       | Visibility of your live app inside Ledger Live | string          | "complete", "searchable", "deep"  |
devs should leave it as default i.e. complete

2023-06-21 13:23 UTC, adrienlacombe-ledger commented on apps/docs/pages/appendix/manifest.mdx
> +| apiVersion       | Specific manifest schema version | string          | *                           |
the default one that comes with the template

2023-06-27 14:14 UTC, ComradeAERGO approved these changes

2023-06-28 12:58 UTC, merged