docs(tutorial): Build a live app from the ground up
LedgerHQ/wallet-api pull request #239
Opened 2023-10-09 11:36 UTC by ComradeAERGO

2023-10-10 07:29 UTC, RamyEB requested changes

2023-10-10 07:29 UTC, RamyEB commented on apps/docs/pages/examples/live-app-creation/manifest.mdx
Already exist here : https://wallet.api.live.ledger.com/examples/test-live-app/import

2023-10-10 07:29 UTC, RamyEB commented on apps/docs/pages/examples/live-app-creation/manifest.mdx
Redirecting or merging could be great

2023-10-10 07:31 UTC, ComradeAERGO commented on apps/docs/pages/examples/live-app-creation/manifest.mdx
You're right!

2023-10-10 07:54 UTC, Justkant reviewed
I cannot see the pages on the documentation deployed for the branch https://wallet-api-git-doc-tutorial-ledgerhq.vercel.app/

2023-10-11 08:37 UTC, tjulien-ledger commented on apps/docs/pages/examples/live-app-creation/configuration.mdx
Similar to @RamyEB 's comment below, we have similar content here: https://wallet.api.live.ledger.com/react/simulator
simulator could be moved to examples under test your live app section instead

2023-10-18 07:52 UTC, merged