Feat/live 10041
LedgerHQ/wallet-api pull request #289
Opened 2024-01-16 15:23 UTC by Wozacosta

### 📝 Description

Handle empty token accounts by using `tokenCurrency` - an (optional) parameter - for the `transaction.sign` and `transaction.signAndBroadcast` wallet api handlers. 

PR ledger live: https://github.com/LedgerHQ/ledger-live/pull/5925 

Jira issue: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-10041

2024-01-18 12:39 UTC, ComradeAERGO approved these changes
LGTM

2024-01-18 13:26 UTC, Justkant requested changes
We need a changeset and I wonder if we haven't forget the `account.receive` handler too

2024-01-19 13:01 UTC, Justkant approved these changes
LGTM if receive actually works

2024-01-19 14:43 UTC, Justkant requested changes
We need the changeset to release that

2024-01-19 15:42 UTC, Justkant approved these changes
LGTM

2024-01-19 15:55 UTC, merged