change manifestVersion to version
LedgerHQ/wallet-api pull request #60
Opened 2022-12-01 14:04 UTC by RamyEB

fixes #59

2022-12-02 09:29 UTC, Justkant reviewed
You just need to call `pnpm changelog` to generate some changeset for your changes.
Because we're are pre 1.0 breaking changes are done using minor version bumps instead of major.

2022-12-05 09:13 UTC, IAmMorrow approved these changes

2022-12-05 11:05 UTC, Justkant requested changes
Still need a changelog plz

2022-12-13 09:15 UTC, Justkant approved these changes
I think we forgot to update the spec for the manifest

2022-12-14 11:39 UTC, merged